{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neuron-agent.fullname" . }}-db
  labels:
    app: neuron-agent
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | default "" | quote }}
{{- end }}
