#!/usr/bin/env bash
# Prepare demo env file template (API keys require DB + generate-key).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.demo.env"
if [[ -f "${OUT}" ]] && grep -q 'NEURON_AGENT_API_KEY=.\+' "${OUT}" 2>/dev/null; then
  echo "Existing ${OUT} already has NEURON_AGENT_API_KEY"
  exit 0
fi

cat > "${OUT}" << 'EOF'
# Generated by scripts/bootstrap-demo.sh
# Set your key after running: go run ./cmd/generate-key from src/ with DB_* matching .env
NEURON_AGENT_API_KEY=
NEURON_AGENT_URL=http://127.0.0.1:8080
EOF
echo "Wrote ${OUT} — set NEURON_AGENT_API_KEY then run scripts/demo.sh"
